# CMAKE generated file: DO NOT EDIT!
# Generated by "MinGW Makefiles" Generator, CMake Version 3.24

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

SHELL = cmd.exe

# The CMake executable.
CMAKE_COMMAND = "C:\Program Files\CMake\bin\cmake.exe"

# The command to remove a file.
RM = "C:\Program Files\CMake\bin\cmake.exe" -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = C:\Users\Boris\Desktop\programming\pl4tform

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = C:\Users\Boris\Desktop\programming\pl4tform

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	"C:\Program Files\CMake\bin\cmake-gui.exe" -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	"C:\Program Files\CMake\bin\cmake.exe" --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start C:\Users\Boris\Desktop\programming\pl4tform\CMakeFiles C:\Users\Boris\Desktop\programming\pl4tform\\CMakeFiles\progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start C:\Users\Boris\Desktop\programming\pl4tform\CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named pl4tform

# Build rule for target.
pl4tform: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 pl4tform
.PHONY : pl4tform

# fast build rule for target.
pl4tform/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\pl4tform.dir\build.make CMakeFiles/pl4tform.dir/build
.PHONY : pl4tform/fast

src/engine/OBB.obj: src/engine/OBB.c.obj
.PHONY : src/engine/OBB.obj

# target to build an object file
src/engine/OBB.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\pl4tform.dir\build.make CMakeFiles/pl4tform.dir/src/engine/OBB.c.obj
.PHONY : src/engine/OBB.c.obj

src/engine/OBB.i: src/engine/OBB.c.i
.PHONY : src/engine/OBB.i

# target to preprocess a source file
src/engine/OBB.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\pl4tform.dir\build.make CMakeFiles/pl4tform.dir/src/engine/OBB.c.i
.PHONY : src/engine/OBB.c.i

src/engine/OBB.s: src/engine/OBB.c.s
.PHONY : src/engine/OBB.s

# target to generate assembly for a file
src/engine/OBB.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\pl4tform.dir\build.make CMakeFiles/pl4tform.dir/src/engine/OBB.c.s
.PHONY : src/engine/OBB.c.s

src/engine/game.obj: src/engine/game.c.obj
.PHONY : src/engine/game.obj

# target to build an object file
src/engine/game.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\pl4tform.dir\build.make CMakeFiles/pl4tform.dir/src/engine/game.c.obj
.PHONY : src/engine/game.c.obj

src/engine/game.i: src/engine/game.c.i
.PHONY : src/engine/game.i

# target to preprocess a source file
src/engine/game.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\pl4tform.dir\build.make CMakeFiles/pl4tform.dir/src/engine/game.c.i
.PHONY : src/engine/game.c.i

src/engine/game.s: src/engine/game.c.s
.PHONY : src/engine/game.s

# target to generate assembly for a file
src/engine/game.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\pl4tform.dir\build.make CMakeFiles/pl4tform.dir/src/engine/game.c.s
.PHONY : src/engine/game.c.s

src/engine/physics.obj: src/engine/physics.c.obj
.PHONY : src/engine/physics.obj

# target to build an object file
src/engine/physics.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\pl4tform.dir\build.make CMakeFiles/pl4tform.dir/src/engine/physics.c.obj
.PHONY : src/engine/physics.c.obj

src/engine/physics.i: src/engine/physics.c.i
.PHONY : src/engine/physics.i

# target to preprocess a source file
src/engine/physics.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\pl4tform.dir\build.make CMakeFiles/pl4tform.dir/src/engine/physics.c.i
.PHONY : src/engine/physics.c.i

src/engine/physics.s: src/engine/physics.c.s
.PHONY : src/engine/physics.s

# target to generate assembly for a file
src/engine/physics.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\pl4tform.dir\build.make CMakeFiles/pl4tform.dir/src/engine/physics.c.s
.PHONY : src/engine/physics.c.s

src/entity/camera.obj: src/entity/camera.c.obj
.PHONY : src/entity/camera.obj

# target to build an object file
src/entity/camera.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\pl4tform.dir\build.make CMakeFiles/pl4tform.dir/src/entity/camera.c.obj
.PHONY : src/entity/camera.c.obj

src/entity/camera.i: src/entity/camera.c.i
.PHONY : src/entity/camera.i

# target to preprocess a source file
src/entity/camera.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\pl4tform.dir\build.make CMakeFiles/pl4tform.dir/src/entity/camera.c.i
.PHONY : src/entity/camera.c.i

src/entity/camera.s: src/entity/camera.c.s
.PHONY : src/entity/camera.s

# target to generate assembly for a file
src/entity/camera.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\pl4tform.dir\build.make CMakeFiles/pl4tform.dir/src/entity/camera.c.s
.PHONY : src/entity/camera.c.s

src/gfx/glad.obj: src/gfx/glad.c.obj
.PHONY : src/gfx/glad.obj

# target to build an object file
src/gfx/glad.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\pl4tform.dir\build.make CMakeFiles/pl4tform.dir/src/gfx/glad.c.obj
.PHONY : src/gfx/glad.c.obj

src/gfx/glad.i: src/gfx/glad.c.i
.PHONY : src/gfx/glad.i

# target to preprocess a source file
src/gfx/glad.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\pl4tform.dir\build.make CMakeFiles/pl4tform.dir/src/gfx/glad.c.i
.PHONY : src/gfx/glad.c.i

src/gfx/glad.s: src/gfx/glad.c.s
.PHONY : src/gfx/glad.s

# target to generate assembly for a file
src/gfx/glad.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\pl4tform.dir\build.make CMakeFiles/pl4tform.dir/src/gfx/glad.c.s
.PHONY : src/gfx/glad.c.s

src/gfx/shader.obj: src/gfx/shader.c.obj
.PHONY : src/gfx/shader.obj

# target to build an object file
src/gfx/shader.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\pl4tform.dir\build.make CMakeFiles/pl4tform.dir/src/gfx/shader.c.obj
.PHONY : src/gfx/shader.c.obj

src/gfx/shader.i: src/gfx/shader.c.i
.PHONY : src/gfx/shader.i

# target to preprocess a source file
src/gfx/shader.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\pl4tform.dir\build.make CMakeFiles/pl4tform.dir/src/gfx/shader.c.i
.PHONY : src/gfx/shader.c.i

src/gfx/shader.s: src/gfx/shader.c.s
.PHONY : src/gfx/shader.s

# target to generate assembly for a file
src/gfx/shader.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\pl4tform.dir\build.make CMakeFiles/pl4tform.dir/src/gfx/shader.c.s
.PHONY : src/gfx/shader.c.s

src/gfx/window.obj: src/gfx/window.c.obj
.PHONY : src/gfx/window.obj

# target to build an object file
src/gfx/window.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\pl4tform.dir\build.make CMakeFiles/pl4tform.dir/src/gfx/window.c.obj
.PHONY : src/gfx/window.c.obj

src/gfx/window.i: src/gfx/window.c.i
.PHONY : src/gfx/window.i

# target to preprocess a source file
src/gfx/window.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\pl4tform.dir\build.make CMakeFiles/pl4tform.dir/src/gfx/window.c.i
.PHONY : src/gfx/window.c.i

src/gfx/window.s: src/gfx/window.c.s
.PHONY : src/gfx/window.s

# target to generate assembly for a file
src/gfx/window.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\pl4tform.dir\build.make CMakeFiles/pl4tform.dir/src/gfx/window.c.s
.PHONY : src/gfx/window.c.s

src/pl4tform.obj: src/pl4tform.c.obj
.PHONY : src/pl4tform.obj

# target to build an object file
src/pl4tform.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\pl4tform.dir\build.make CMakeFiles/pl4tform.dir/src/pl4tform.c.obj
.PHONY : src/pl4tform.c.obj

src/pl4tform.i: src/pl4tform.c.i
.PHONY : src/pl4tform.i

# target to preprocess a source file
src/pl4tform.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\pl4tform.dir\build.make CMakeFiles/pl4tform.dir/src/pl4tform.c.i
.PHONY : src/pl4tform.c.i

src/pl4tform.s: src/pl4tform.c.s
.PHONY : src/pl4tform.s

# target to generate assembly for a file
src/pl4tform.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\pl4tform.dir\build.make CMakeFiles/pl4tform.dir/src/pl4tform.c.s
.PHONY : src/pl4tform.c.s

src/utils/helper.obj: src/utils/helper.c.obj
.PHONY : src/utils/helper.obj

# target to build an object file
src/utils/helper.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\pl4tform.dir\build.make CMakeFiles/pl4tform.dir/src/utils/helper.c.obj
.PHONY : src/utils/helper.c.obj

src/utils/helper.i: src/utils/helper.c.i
.PHONY : src/utils/helper.i

# target to preprocess a source file
src/utils/helper.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\pl4tform.dir\build.make CMakeFiles/pl4tform.dir/src/utils/helper.c.i
.PHONY : src/utils/helper.c.i

src/utils/helper.s: src/utils/helper.c.s
.PHONY : src/utils/helper.s

# target to generate assembly for a file
src/utils/helper.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\pl4tform.dir\build.make CMakeFiles/pl4tform.dir/src/utils/helper.c.s
.PHONY : src/utils/helper.c.s

src/utils/mesh.obj: src/utils/mesh.c.obj
.PHONY : src/utils/mesh.obj

# target to build an object file
src/utils/mesh.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\pl4tform.dir\build.make CMakeFiles/pl4tform.dir/src/utils/mesh.c.obj
.PHONY : src/utils/mesh.c.obj

src/utils/mesh.i: src/utils/mesh.c.i
.PHONY : src/utils/mesh.i

# target to preprocess a source file
src/utils/mesh.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\pl4tform.dir\build.make CMakeFiles/pl4tform.dir/src/utils/mesh.c.i
.PHONY : src/utils/mesh.c.i

src/utils/mesh.s: src/utils/mesh.c.s
.PHONY : src/utils/mesh.s

# target to generate assembly for a file
src/utils/mesh.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\pl4tform.dir\build.make CMakeFiles/pl4tform.dir/src/utils/mesh.c.s
.PHONY : src/utils/mesh.c.s

# Help Target
help:
	@echo The following are some of the valid targets for this Makefile:
	@echo ... all (the default if no target is provided)
	@echo ... clean
	@echo ... depend
	@echo ... edit_cache
	@echo ... rebuild_cache
	@echo ... pl4tform
	@echo ... src/engine/OBB.obj
	@echo ... src/engine/OBB.i
	@echo ... src/engine/OBB.s
	@echo ... src/engine/game.obj
	@echo ... src/engine/game.i
	@echo ... src/engine/game.s
	@echo ... src/engine/physics.obj
	@echo ... src/engine/physics.i
	@echo ... src/engine/physics.s
	@echo ... src/entity/camera.obj
	@echo ... src/entity/camera.i
	@echo ... src/entity/camera.s
	@echo ... src/gfx/glad.obj
	@echo ... src/gfx/glad.i
	@echo ... src/gfx/glad.s
	@echo ... src/gfx/shader.obj
	@echo ... src/gfx/shader.i
	@echo ... src/gfx/shader.s
	@echo ... src/gfx/window.obj
	@echo ... src/gfx/window.i
	@echo ... src/gfx/window.s
	@echo ... src/pl4tform.obj
	@echo ... src/pl4tform.i
	@echo ... src/pl4tform.s
	@echo ... src/utils/helper.obj
	@echo ... src/utils/helper.i
	@echo ... src/utils/helper.s
	@echo ... src/utils/mesh.obj
	@echo ... src/utils/mesh.i
	@echo ... src/utils/mesh.s
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 0
.PHONY : cmake_check_build_system

